//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using HoteManagement.Caching;
using HoteManagement.Data;
using HoteManagement.Infrastructure.Domain;
using HoteManagement.Service.Events;
using System;
using System.Collections.Generic;

namespace HoteManagement.Service.Model
{
    public abstract class ApplicationService : IApplicationService
    {
        protected readonly IRepository<Domain.account_goods> _account_goodsRepository;
        protected readonly IRepository<Domain.Accounts_Roles> _accounts_rolesRepository;
        protected readonly IRepository<Domain.Accounts_UserRoles> _accounts_userrolesRepository;
        protected readonly IRepository<Domain.Accounts_Users> _accounts_usersRepository;
        protected readonly IRepository<Domain.AddPrice> _addpriceRepository;
        protected readonly IRepository<Domain.apartment> _apartmentRepository;
        protected readonly IRepository<Domain.banner> _bannerRepository;
        protected readonly IRepository<Domain.Book_Rdetail> _book_rdetailRepository;
        protected readonly IRepository<Domain.book_room> _book_roomRepository;
        protected readonly IRepository<Domain.BookState> _bookstateRepository;
        protected readonly IRepository<Domain.card_type> _card_typeRepository;
        protected readonly IRepository<Domain.cCall> _ccallRepository;
        protected readonly IRepository<Domain.cDepartment> _cdepartmentRepository;
        protected readonly IRepository<Domain.cIndustry> _cindustryRepository;
        protected readonly IRepository<Domain.comm_unit> _comm_unitRepository;
        protected readonly IRepository<Domain.Commission> _commissionRepository;
        protected readonly IRepository<Domain.Contacts> _contactsRepository;
        protected readonly IRepository<Domain.cost_type> _cost_typeRepository;
        protected readonly IRepository<Domain.cPost> _cpostRepository;
        protected readonly IRepository<Domain.cprotocol> _cprotocolRepository;
        protected readonly IRepository<Domain.cprotocolPrice> _cprotocolpriceRepository;
        protected readonly IRepository<Domain.cpType> _cptypeRepository;
        protected readonly IRepository<Domain.csysType> _csystypeRepository;
        protected readonly IRepository<Domain.customer> _customerRepository;
        protected readonly IRepository<Domain.customerState> _customerstateRepository;
        protected readonly IRepository<Domain.customerType> _customertypeRepository;
        protected readonly IRepository<Domain.Entry> _entryRepository;
        protected readonly IRepository<Domain.ExceedScheme> _exceedschemeRepository;
        protected readonly IRepository<Domain.floor_ld> _floor_ldRepository;
        protected readonly IRepository<Domain.floor_manage> _floor_manageRepository;
        protected readonly IRepository<Domain.FtSet> _ftsetRepository;
        protected readonly IRepository<Domain.Goods> _goodsRepository;
        protected readonly IRepository<Domain.goods_account> _goods_accountRepository;
        protected readonly IRepository<Domain.guest_source> _guest_sourceRepository;
        protected readonly IRepository<Domain.hour_room> _hour_roomRepository;
        protected readonly IRepository<Domain.hourse_scheme> _hourse_schemeRepository;
        protected readonly IRepository<Domain.info> _infoRepository;
        protected readonly IRepository<Domain.member> _memberRepository;
        protected readonly IRepository<Domain.memberState> _memberstateRepository;
        protected readonly IRepository<Domain.memberType> _membertypeRepository;
        protected readonly IRepository<Domain.Menu> _menuRepository;
        protected readonly IRepository<Domain.meth_pay> _meth_payRepository;
        protected readonly IRepository<Domain.modes> _modesRepository;
        protected readonly IRepository<Domain.mRecords> _mrecordsRepository;
        protected readonly IRepository<Domain.mtPrice> _mtpriceRepository;
        protected readonly IRepository<Domain.occu_infor> _occu_inforRepository;
        protected readonly IRepository<Domain.occu_informx> _occu_informxRepository;
        protected readonly IRepository<Domain.order_infor> _order_inforRepository;
        protected readonly IRepository<Domain.paymentMoney> _paymentmoneyRepository;
        protected readonly IRepository<Domain.price_type> _price_typeRepository;
        protected readonly IRepository<Domain.print> _printRepository;
        protected readonly IRepository<Domain.real_mode> _real_modeRepository;
        protected readonly IRepository<Domain.real_state> _real_stateRepository;
        protected readonly IRepository<Domain.Remaker> _remakerRepository;
        protected readonly IRepository<Domain.Repair> _repairRepository;
        protected readonly IRepository<Domain.RoleMenu> _rolemenuRepository;
        protected readonly IRepository<Domain.room_feature> _room_featureRepository;
        protected readonly IRepository<Domain.room_number> _room_numberRepository;
        protected readonly IRepository<Domain.room_state> _room_stateRepository;
        protected readonly IRepository<Domain.room_type> _room_typeRepository;
        protected readonly IRepository<Domain.room_type_image> _room_type_imageRepository;
        protected readonly IRepository<Domain.sale_man> _sale_manRepository;
        protected readonly IRepository<Domain.Shift> _shiftRepository;
        protected readonly IRepository<Domain.Shift_Exc> _shift_excRepository;
        protected readonly IRepository<Domain.shopInfo> _shopinfoRepository;
        protected readonly IRepository<Domain.Sincethehous> _sincethehousRepository;
        protected readonly IRepository<Domain.SuoRoom> _suoroomRepository;
        protected readonly IRepository<Domain.SuoSys> _suosysRepository;
        protected readonly IRepository<Domain.SysParamter> _sysparamterRepository;
        protected readonly IRepository<Domain.TypeScheme> _typeschemeRepository;
        protected readonly IRepository<Domain.UserInfo> _userinfoRepository;
        protected readonly IRepository<Domain.Users> _usersRepository;
        protected readonly IRepository<Domain.userType> _usertypeRepository;
        protected readonly IRepository<Domain.ZD_hourse> _zd_hourseRepository;

        protected readonly IDbContext _dbcontext;
        protected readonly IRedis _redishelper;
        protected readonly IEventPublisher _eventPublisher;
        protected readonly ILogger _logger;


        public ApplicationService(
            IRepository<Domain.account_goods> account_goodsRepository,
                IRepository<Domain.Accounts_Roles> accounts_rolesRepository,
                IRepository<Domain.Accounts_UserRoles> accounts_userrolesRepository,
                IRepository<Domain.Accounts_Users> accounts_usersRepository,
                IRepository<Domain.AddPrice> addpriceRepository,
                IRepository<Domain.apartment> apartmentRepository,
                IRepository<Domain.banner> bannerRepository,
                IRepository<Domain.Book_Rdetail> book_rdetailRepository,
                IRepository<Domain.book_room> book_roomRepository,
                IRepository<Domain.BookState> bookstateRepository,
                IRepository<Domain.card_type> card_typeRepository,
                IRepository<Domain.cCall> ccallRepository,
                IRepository<Domain.cDepartment> cdepartmentRepository,
                IRepository<Domain.cIndustry> cindustryRepository,
                IRepository<Domain.comm_unit> comm_unitRepository,
                IRepository<Domain.Commission> commissionRepository,
                IRepository<Domain.Contacts> contactsRepository,
                IRepository<Domain.cost_type> cost_typeRepository,
                IRepository<Domain.cPost> cpostRepository,
                IRepository<Domain.cprotocol> cprotocolRepository,
                IRepository<Domain.cprotocolPrice> cprotocolpriceRepository,
                IRepository<Domain.cpType> cptypeRepository,
                IRepository<Domain.csysType> csystypeRepository,
                IRepository<Domain.customer> customerRepository,
                IRepository<Domain.customerState> customerstateRepository,
                IRepository<Domain.customerType> customertypeRepository,
                IRepository<Domain.Entry> entryRepository,
                IRepository<Domain.ExceedScheme> exceedschemeRepository,
                IRepository<Domain.floor_ld> floor_ldRepository,
                IRepository<Domain.floor_manage> floor_manageRepository,
                IRepository<Domain.FtSet> ftsetRepository,
                IRepository<Domain.Goods> goodsRepository,
                IRepository<Domain.goods_account> goods_accountRepository,
                IRepository<Domain.guest_source> guest_sourceRepository,
                IRepository<Domain.hour_room> hour_roomRepository,
                IRepository<Domain.hourse_scheme> hourse_schemeRepository,
                IRepository<Domain.info> infoRepository,
                IRepository<Domain.member> memberRepository,
                IRepository<Domain.memberState> memberstateRepository,
                IRepository<Domain.memberType> membertypeRepository,
                IRepository<Domain.Menu> menuRepository,
                IRepository<Domain.meth_pay> meth_payRepository,
                IRepository<Domain.modes> modesRepository,
                IRepository<Domain.mRecords> mrecordsRepository,
                IRepository<Domain.mtPrice> mtpriceRepository,
                IRepository<Domain.occu_infor> occu_inforRepository,
                IRepository<Domain.occu_informx> occu_informxRepository,
                IRepository<Domain.order_infor> order_inforRepository,
                IRepository<Domain.paymentMoney> paymentmoneyRepository,
                IRepository<Domain.price_type> price_typeRepository,
                IRepository<Domain.print> printRepository,
                IRepository<Domain.real_mode> real_modeRepository,
                IRepository<Domain.real_state> real_stateRepository,
                IRepository<Domain.Remaker> remakerRepository,
                IRepository<Domain.Repair> repairRepository,
                IRepository<Domain.RoleMenu> rolemenuRepository,
                IRepository<Domain.room_feature> room_featureRepository,
                IRepository<Domain.room_number> room_numberRepository,
                IRepository<Domain.room_state> room_stateRepository,
                IRepository<Domain.room_type> room_typeRepository,
                IRepository<Domain.room_type_image> room_type_imageRepository,
                IRepository<Domain.sale_man> sale_manRepository,
                IRepository<Domain.Shift> shiftRepository,
                IRepository<Domain.Shift_Exc> shift_excRepository,
                IRepository<Domain.shopInfo> shopinfoRepository,
                IRepository<Domain.Sincethehous> sincethehousRepository,
                IRepository<Domain.SuoRoom> suoroomRepository,
                IRepository<Domain.SuoSys> suosysRepository,
                IRepository<Domain.SysParamter> sysparamterRepository,
                IRepository<Domain.TypeScheme> typeschemeRepository,
                IRepository<Domain.UserInfo> userinfoRepository,
                IRepository<Domain.Users> usersRepository,
                IRepository<Domain.userType> usertypeRepository,
                IRepository<Domain.ZD_hourse> zd_hourseRepository,
                IDbContext dbcontext,
                IRedis redishelper,
                IEventPublisher eventPublisher,
                ILogger logger

        )
        {

            this._account_goodsRepository = account_goodsRepository;

            this._accounts_rolesRepository = accounts_rolesRepository;

            this._accounts_userrolesRepository = accounts_userrolesRepository;

            this._accounts_usersRepository = accounts_usersRepository;

            this._addpriceRepository = addpriceRepository;

            this._apartmentRepository = apartmentRepository;

            this._bannerRepository = bannerRepository;

            this._book_rdetailRepository = book_rdetailRepository;

            this._book_roomRepository = book_roomRepository;

            this._bookstateRepository = bookstateRepository;

            this._card_typeRepository = card_typeRepository;

            this._ccallRepository = ccallRepository;

            this._cdepartmentRepository = cdepartmentRepository;

            this._cindustryRepository = cindustryRepository;

            this._comm_unitRepository = comm_unitRepository;

            this._commissionRepository = commissionRepository;

            this._contactsRepository = contactsRepository;

            this._cost_typeRepository = cost_typeRepository;

            this._cpostRepository = cpostRepository;

            this._cprotocolRepository = cprotocolRepository;

            this._cprotocolpriceRepository = cprotocolpriceRepository;

            this._cptypeRepository = cptypeRepository;

            this._csystypeRepository = csystypeRepository;

            this._customerRepository = customerRepository;

            this._customerstateRepository = customerstateRepository;

            this._customertypeRepository = customertypeRepository;

            this._entryRepository = entryRepository;

            this._exceedschemeRepository = exceedschemeRepository;

            this._floor_ldRepository = floor_ldRepository;

            this._floor_manageRepository = floor_manageRepository;

            this._ftsetRepository = ftsetRepository;

            this._goodsRepository = goodsRepository;

            this._goods_accountRepository = goods_accountRepository;

            this._guest_sourceRepository = guest_sourceRepository;

            this._hour_roomRepository = hour_roomRepository;

            this._hourse_schemeRepository = hourse_schemeRepository;

            this._infoRepository = infoRepository;

            this._memberRepository = memberRepository;

            this._memberstateRepository = memberstateRepository;

            this._membertypeRepository = membertypeRepository;

            this._menuRepository = menuRepository;

            this._meth_payRepository = meth_payRepository;

            this._modesRepository = modesRepository;

            this._mrecordsRepository = mrecordsRepository;

            this._mtpriceRepository = mtpriceRepository;

            this._occu_inforRepository = occu_inforRepository;

            this._occu_informxRepository = occu_informxRepository;

            this._order_inforRepository = order_inforRepository;

            this._paymentmoneyRepository = paymentmoneyRepository;

            this._price_typeRepository = price_typeRepository;

            this._printRepository = printRepository;

            this._real_modeRepository = real_modeRepository;

            this._real_stateRepository = real_stateRepository;

            this._remakerRepository = remakerRepository;

            this._repairRepository = repairRepository;

            this._rolemenuRepository = rolemenuRepository;

            this._room_featureRepository = room_featureRepository;

            this._room_numberRepository = room_numberRepository;

            this._room_stateRepository = room_stateRepository;

            this._room_typeRepository = room_typeRepository;

            this._room_type_imageRepository = room_type_imageRepository;

            this._sale_manRepository = sale_manRepository;

            this._shiftRepository = shiftRepository;

            this._shift_excRepository = shift_excRepository;

            this._shopinfoRepository = shopinfoRepository;

            this._sincethehousRepository = sincethehousRepository;

            this._suoroomRepository = suoroomRepository;

            this._suosysRepository = suosysRepository;

            this._sysparamterRepository = sysparamterRepository;

            this._typeschemeRepository = typeschemeRepository;

            this._userinfoRepository = userinfoRepository;

            this._usersRepository = usersRepository;

            this._usertypeRepository = usertypeRepository;

            this._zd_hourseRepository = zd_hourseRepository;
            this._dbcontext = dbcontext;
            this._eventPublisher = eventPublisher;
            this._redishelper = redishelper;
            this._logger = logger;
        }
    }
}
