//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class room_featureMap : BaseEntityTypeConfiguration<HoteManagement.Domain.room_feature>
    {
       public room_featureMap()
       {
          this.HasKey(t => t.Id);
          this.Property(t => t.room_feature_name).HasMaxLength(50);
          this.Property(t => t.remark).HasMaxLength();
          this.Property(t => t.createtime);
          this.Property(t => t.updatetime);
       }
    }
}
