//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Console.Model
{
    
    
    public class sysdiagramsMap : BaseEntityTypeConfiguration<HoteManagement.Domain.sysdiagrams>
    {
       public sysdiagramsMap()
       {
          this.Property(t => t.name).HasMaxLength(128);
          this.Property(t => t.principal_id);
          this.Property(t => t.diagram_id);
          this.Property(t => t.version);
          this.Property(t => t.definition);
       }
    }
}
