//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace HoteManagement.Domain
{
    
    
    public class RoleMenu : BaseEntity
    {
        
        public Nullable<long> RoleID { get; set; }
        public Nullable<long> Menu_id { get; set; }
        public Nullable<long> Menu_pid { get; set; }
        
        
    }
}
